### ISSUE TITLE
Towards Supporting Skip Connections

### ISSUE THREAD

**Issue by vse-motec** [Hahn-Schickard/Automatic-Structured-Pruning#26]
I am currently working an adding support to prune networks with skip connections.
If you are interested, I can provide all steps towards this goal as individual pull requests (as soon as I have them).

The first step is checking each layers's parent during filter / node deletion in the functions "delete_filter" and "delete_dense_neuron".
So far, these functions assume that a layer at index (i+1) has its parent at index i. However, since this is not the case for skip connections, we have to add parent layer checking.

This additional check should not affect your code in a negative way. I can provide the corresponding pull request for you to run your tests.

**Comment by konegen** [comment]
Hi, this sounds very interesting, If you want to be a part of the development, we would be very happy.

Kind regards
Daniel

**Comment by vse-motec** [comment]
Yes, I would like to contribute. Short update: there has been a delay because I was working on an outdated version of this repository. Need some more testing that the merge went smoothly. Get back to this next week.

**Comment by konegen** [comment]
Hi and sorry for the late answer.
Thank you very much for your work. We can also discuss it in a call.

Best regards
Daniel

**Comment by vse-motec** [comment]
Hi all, 
I have now added the missing functionality to prune all conv layers. So far only tested with the provided Jupyter Notebook (sequential model) and with YoloV3 (functional model).
Best regards
Viktor

**Comment by konegen** [comment]
Hey,
thank you very much for your work and the second pull request.

Best regards
Daniel
