### ISSUE TITLE
Ask for help about Automatic-Structured-Pruning

### ISSUE THREAD

**Issue by 1102540794** [Hahn-Schickard/Automatic-Structured-Pruning#27]
I am very interested in this knowledge and would like to further study the relevant theoretical content.

I want to learn the theory of automatic structural pruning.

I would appreciate it if you could share relevant papers or materials with me. (Preferably in written form.)

I promise to use it only for my own study. 

My e-mail is 1102540794@my.swjtu.edu.cn

Looking forward to your early reply.

Best regards,
Jack Sun

**Comment by vse-motec** [comment]
Hello Jack Sun,

this repository uses structural pruning according to magnitude metrics. You can find more information e.g. in the survey paper https://arxiv.org/abs/2101.09671

Look for Section 3.1 - this is what is done in this repo (not all of it, but pruning according to L1 and L2 metrics).

Hope this helps,
Viktor

**Comment by 1102540794** [comment]
OK! I get it！
Thank you very much for your reply！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hahn-Schickard/Automatic-Structured-Pruning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 晚上7:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hahn-Schickard/Automatic-Structured-Pruning] Ask for help about Automatic-Structured-Pruning (Issue #27)





 
Hello Jack Sun,
 
this repository uses structural pruning according to magnitude metrics. You can find more information e.g. in the survey paper https://arxiv.org/abs/2101.09671
 
Look for Section 3.1 - this is what is done in this repo (not all of it, but pruning according to L1 and L2 metrics).
 
Hope this helps,
 Viktor
